# config file for static transform publisher between base_link and laser_link on Kilotron
frame_id: "base_link" 
child_frame_id: "laser_link"
x: 0        # center of car
y: 0        # center of car
z: 0.0762   # 3" up from center of base (TODO: actually measure)
yaw: 0
pitch: 0
roll: 0
period: 100