TrajectoryPlannerROS: # parameters for Gigatron 
  max_vel_x: 8
  min_vel_x: 0.5
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  xy_goal_tolerance: 2
  yaw_goal_tolerance: 3.69 # don't really care which direction it's pointing
  free_goal_vel: true # ?
