TebLocalPlannerROS: # parameters for Gigatron with race body

 odom_topic: odom
 map_frame: /odom
    
 # Trajectory
  
 teb_autosize: True                       # (default)
 dt_ref: 0.3                              # (default)
 dt_hysteresis: 0.1                       # (default)
 global_plan_overwrite_orientation: True  # (default)
 max_global_plan_lookahead_dist: 3.0      # (default)
 feasibility_check_no_poses: 5            # (default)
    
 # Robot
         
 max_vel_x: 8 
 max_vel_x_backwards: 8 
 max_vel_theta: 0.3       # (default) TODO: update
 acc_lim_x: 0.5           # (default)
 acc_lim_theta: 0.5       # (default)
 min_turning_radius: 0.457 # TODO: update
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "line"
   line_start: [0.55, 0.0] # for type "line"
   line_end: [-0.5, 0.0] # for type "line"

 # GoalTolerance
    
 xy_goal_tolerance: 2
 yaw_goal_tolerance: 6.9 # don't really care which direction it's pointing
 free_goal_vel: False # ?
    
 # Obstacles
    
 min_obstacle_dist: 0.5 # wheelbase width is 0.58
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
