#! /usr/bin/env python

# cmd_vel_to_drive
# script for converting geometry_msgs/Twist to gigatron/Drive messages
# 
# @author  Syler Wagner  <syler@mit.edu>
# @date    2016-09-11    syler   creation


import rospy, math
from sensor_msgs.msg import Imu

import tf
from tf.transformations import euler_from_quaternion

def imu_callback(msg):
# find current orientation of robot based on odometry (quaternion coordinates)
    xOr = msg.orientation.x
    yOr = msg.orientation.y
    zOr = msg.orientation.z
    wOr = msg.orientation.w

    # find orientation of robot (Euler coordinates)
    (roll, pitch, yaw) = euler_from_quaternion([xOr, yOr, zOr, wOr])

    # find currentAngle of robot (equivalent to yaw)
    # now that you have yaw, the robot's pose is completely defined by (currentX, currentY, currentAngle)
    rospy.loginfo("roll: %4.1f pitch: %4.1f yaw: %4.1f", roll, pitch, yaw)

if __name__ == '__main__': 
  try:
    
    rospy.init_node('quat_to_rpy')
        
    imu_topic = rospy.get_param('imu_topic', '/imu/data') 
    
    rospy.Subscriber(imu_topic, Imu, imu_callback, queue_size=1)
    
    rospy.spin()
    
  except rospy.ROSInterruptException:
    pass
