#! /usr/bin/env python

'''
  Software License Agreement (BSD License)

  Copyright (c) 2017, Cult Classic Racing.
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above
     copyright notice, this list of conditions and the following
     disclaimer in the documentation and/or other materials provided
     with the distribution.
  3. Neither the name of the copyright holder nor the names of its 
     contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
  
'''

# quat_to_rpy
# script for converting quaternion to roll pitch yaw
# 
# @author  Syler Wagner  <syler@mit.edu>
# @date    2016-09-11    syler   creation


import rospy, math
from sensor_msgs.msg import Imu

import tf
from tf.transformations import euler_from_quaternion

def imu_callback(msg):
# find current orientation of robot based on odometry (quaternion coordinates)
    xOr = msg.orientation.x
    yOr = msg.orientation.y
    zOr = msg.orientation.z
    wOr = msg.orientation.w

    # find orientation of robot (Euler coordinates)
    (roll, pitch, yaw) = euler_from_quaternion([xOr, yOr, zOr, wOr])

    # find currentAngle of robot (equivalent to yaw)
    # now that you have yaw, the robot's pose is completely defined by (currentX, currentY, currentAngle)
    rospy.loginfo("roll: %4.1f pitch: %4.1f yaw: %4.1f", roll, pitch, yaw)

if __name__ == '__main__': 
  try:
    
    rospy.init_node('quat_to_rpy')
        
    imu_topic = rospy.get_param('imu_topic', '/imu/data') 
    
    rospy.Subscriber(imu_topic, Imu, imu_callback, queue_size=1)
    
    rospy.spin()
    
  except rospy.ROSInterruptException:
    pass
