local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0 # [Hz] rate at which costmap publishes visualization information
  static_map: false
  rolling_window: true # true means costmap stays centered around robot as it moves through the world
  width: 6.0  # [m] width of costmap
  height: 6.0 # [m] height of costmap
  resolution: 0.05 # [m/cell] resolution of costmap, usually the same as resolution of static map
