name: "Gigatron"
steering_pwm_range: 255
steering_angle_range: 0.8726646   # [radians] 50 degrees
gear_ratio: 0.18333               # 11.0 : 60.0 drive motors : wheels
wheel_radius: 0.12446             # [m] 4.9 inches
wheelbase_width: 0.5842           # [m] 23 inches
max_motor_rpm: 5310.0		  # spec sheet says 5,310 (+/- 10%) unloaded but empirically doesn't go above 2000
