name: "Kilotron"
steering_pwm_range: 255
steering_angle_range: 0.76096 # [radians] 43.6 degrees
gear_ratio: 1                 # drive motors / wheels
car_length: 0.254             # [m]
car_height: 0.127             # [m]
wheel_diameter: 0.0666        # [m]
wheel_width: 0.0254           # [m]
wheelbase_width: 0.1778       # [m]
max_motor_rpm: 200.0
