#!/bin/bash

# rosbag_exclude
#
# Bash script for removing navigation stack output from a rosbag
# 
# @author   Syler Wagner    <syler@mit.edu>
#
# @date     2016-09-18      creation

INBAG=$1
INBAG_BASENAME=${INBAG%.*}
if [ "$#" -gt 1 ]; then
    OUTBAG=$2
else
	OUTBAG=$INBAG_BASENAME'_no_tf.bag'
fi
echo ' [>  ] Filtering rosbag to '$OUTBAG

echo ' [>> ] Excluding topics: '


EXCLUDE='('

# auto-generate python expression as input for rosbag filter from config file
while read line; do 
	EXCLUDE=$EXCLUDE'topic != "'$line'" and '; 
	echo '       - '$line
done < `rospack find gigatron`/config/rosbag_exclude/$3'.yaml'

TF_EXCLUDE='topic == "/tf" and m.transforms[0].header.frame_id != "/map" and m.transforms[0].child_frame_id != "/odom"'
echo '       - '$TF_EXCLUDE

EXCLUDE=$EXCLUDE'topic != "/tf") or ('$TF_EXCLUDE')'
echo 
echo 'rosbag filter' $INBAG $OUTBAG \'$EXCLUDE\'
rosbag filter $INBAG $OUTBAG \'$EXCLUDE\'

echo ' [>>>] Done.'
