#! /usr/bin/env python

# save_training_data
#
# Python script for saving LIDAR and RC inputs as training data for end-to-end learning
# 
# @author   Syler Wagner	<syler@mit.edu>
#
# @date	 2017-01-13	  creation

import csv
import rospy
from gigatron.msg import State, ExtendedState   
from gigatron_hardware.msg import Radio, Motors 
from sensor_msgs.msg import LaserScan  

import csv

class TrainingDataSaver():

	def __init__(self):
		# init
		# get parameters 
		# scan topic
		scan_topic = rospy.get_param('~scan_topic', '/scan_rp') 
		# radio topic
		radio_topic = rospy.get_param('~radio_topic', '/arduino/radio') 
		# motor topic
		motor_topic = rospy.get_param('~motor_topic', '/arduino/motors') 
		# state topic
		state_topic = rospy.get_param('~state_topic', '/state') 

		# output folder
		self._output_folder = rospy.get_param('~output_folder', '/Users/Syler/gigann/20160916_avc_track/') 

		# self._steering_angle_range = rospy.get_param("car/steering_angle_range")

		# subscribers
		rospy.Subscriber(scan_topic, LaserScan, self.scan_callback)
		rospy.Subscriber(radio_topic, Radio, self.radio_callback)
		rospy.Subscriber(motor_topic, Motors, self.motor_callback)

		if rospy.get_param('~extended_state', True):
			rospy.Subscriber(state_topic, ExtendedState, self.state_callback)
		else:
			rospy.Subscriber(state_topic, State, self.state_callback)

		# initialize values
		self._rc = False
		self._throttle = 1500
		self._angle = 128
		self._v = 0.0 # current velocity

		self._i = 0

		rospy.loginfo("Saving output to %s", self._output_folder)
		rospy.loginfo("Waiting for first LaserScan message on %s...", scan_topic)
		rospy.spin()

	# laser scan callback method
	# save forward 180 degrees of scan as a row in csv file if RC
	def scan_callback(self, msg):
		timestamp_string = str(msg.header.stamp.secs)+'.'+format(msg.header.stamp.nsecs, '09')

		
		if self._rc: 
			# add angle check because of some suspect data
			# check if velocity is greater than 0.5
			if self._v > 0.5 and self._angle > 0:
				myfile = open(self._output_folder+timestamp_string+'_scan'+'.csv', 'wb')
				wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
				wr.writerow(msg.ranges)
				wr.writerow(msg.intensities)
				myfile.close()

				myfile = open(self._output_folder+timestamp_string+'_command'+'.csv', 'wb')
				wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
				wr.writerow([self._throttle, self._angle])
				myfile.close()

				rospy.logwarn('Saved frame %d. Angle: %d Throttle: %d', self._i, self._angle, self._throttle)
				self._i = self._i + 1
			else:
				rospy.loginfo('Discarding frame at time %s because car was barely moving', timestamp_string)
		else:
			rospy.loginfo('Discarding non-RC mode frame at time %s', timestamp_string)

	# state callback
	# update variable keeping track of whether current state is RC
	def state_callback(self, msg):
		self._v = msg.drive.vel_left
		if msg.mode == "RC":
			self._rc = True
		else:
			self._rc = False

	# radio callback
	# update variable keeping track of last RC commands
	def radio_callback(self, msg):
		# self._throttle =  msg.speed_left
		self._angle = msg.angle

	# motor callback
	# update variable keeping track of last motor commands
	def motor_callback(self, msg):
		self._throttle = (msg.usec_left - 1500) / 2

if __name__=="__main__":
	rospy.init_node('save_training_data')
	
	try:
		TrainingDataSaver()
	except rospy.ROSInterruptException:
		print " [!!!] save_training_data: ROSInterruptException!"
		pass
