#! /usr/bin/env python

'''
  Software License Agreement (BSD License)

  Copyright (c) 2017, Cult Classic Racing.
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above
     copyright notice, this list of conditions and the following
     disclaimer in the documentation and/or other materials provided
     with the distribution.
  3. Neither the name of the copyright holder nor the names of its 
     contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
  
'''

# drive_test_pub
#
# Python script for publishing Drive messages (and optionally 
# relative altitude messages) with custom frame id
# 
# @author   Syler Wagner	<syler@mit.edu>
#
# @date	 2016-09-11	  creation

import rospy
import sys
from gigatron_msgs.msg import DriveStamped   # for sending commands

class DriveTestPub():

	def __init__(self):
	
		self.topic = rospy.get_param('~topic', 'command/drive') # 
		# Drive message publisher
		drive_test_pub = rospy.Publisher(self.topic, DriveStamped, queue_size=1)

		msg = DriveStamped()

		if len(sys.argv) == 4:
			msg.drive.angle = float(sys.argv[1])
			msg.drive.vel_left = float(sys.argv[2]) 
			msg.drive.vel_right = float(sys.argv[3])
		else:
			rospy.logerr('drive_test_pub used with incorrect arguments!')
			rospy.logerr('Usage:')
			rospy.logerr('   rosrun gigatron_hardware drive_test_pub <ANGLE> <V_LEFT> <V_RIGHT>')
			sys.exit(-1)
			
		while not rospy.is_shutdown():
			drive_test_pub.publish(msg)
			rospy.loginfo('Published angle: %4.1f, vel_left: %4.1f, vel_right: %4.1f', msg.drive.angle, msg.drive.vel_left, msg.drive.vel_right)
			rospy.sleep(1)

if __name__=="__main__":
	rospy.init_node('drive_test_pub')
	
	try:
		DriveTestPub()
	except rospy.ROSInterruptException:
		print " [!!!] drive_test_pub: ROSInterruptException!"
		pass


