scan_filter_chain:
- name: koolaid_angle_filter
  type: LaserScanAngleFilter
  params:
    upper_angle: 0.140
    lower_angle: 2.800
# pi/6: 0.52359877559
# pi/2: 1.5707963267948966
#2*pi: 6.28318531
#pi: 3.14159265359

#Note that positve and negative flips at +-180. There is no 270, it's -90. 