<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro"
    name="kilotron">

    <xacro:include filename="$(find gigatron_hardware)/urdf/common.urdf.xacro" />
    <xacro:include filename="$(find gigatron_hardware)/urdf/sensors/zed.urdf.xacro" />
    <xacro:include filename="$(find gigatron_hardware)/urdf/sensors/bno055_imu.urdf.xacro" />
    <xacro:include filename="$(find gigatron_hardware)/urdf/sensors/rplidar.urdf.xacro" />

    <!-- Dimension Macros -->
    <xacro:property name="car_length" value="0.254" /> <!-- 10" -->
    <xacro:property name="wheelbase_width" value="0.1778" />
    <xacro:property name="car_height" value="0.127" /> <!-- 5" -->
    <xacro:property name="wheel_radius" value="0.0333" />
    <xacro:property name="wheel_width" value="0.0254" /> <!-- 1" -->
    
    <!-- IMU placement relative to base_link -->
    <xacro:property name="imu_x" value="0" /> 
    <xacro:property name="imu_y" value="0" />
    <xacro:property name="imu_z" value="0.00637" /> 

    <!-- LIDAR placement relative to base_link -->
    <xacro:property name="lidar_x" value="0.1016" /> 
    <xacro:property name="lidar_y" value="0" />
    <xacro:property name="lidar_z" value="0.05715" /> 
    <xacro:property name="lidar_yaw" value="${M_PI}" />

    <!-- ZED placement relative to base_link -->
    <xacro:property name="zed_x" value="0.1778" /> 
    <xacro:property name="zed_y" value="0" />
    <xacro:property name="zed_z" value="0" /> 
    <xacro:property name="zed_cam_separation" value="0.12065" /> 

    <!-- base_footprint (ground) to base_link -->
    <link name="base_footprint" />
    <joint name="base_link_footprint_joint" type="fixed" >
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${car_height/2+0.0508-wheel_radius}" rpy="0 0 0" />
    </joint>  

    <!-- Main body -->
    <link name="base_link">
        <inertial>
            <mass value="0.2" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.2" ixy="0.0"  ixz="0.0"  iyy="0.2"  iyz="0.0"  izz="0.2" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${car_length} ${wheelbase_width} ${car_height}" />
            </geometry>
            <material name="Grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${car_length} ${wheelbase_width} ${car_height}" />
            </geometry>
        </collision>
    </link>

    <!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="revolute" >
        <limit lower="-0.76096" upper="0.76096" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0.127 0.089 -0.0508" rpy="0 0 0" /> <!-- 5, 3.5, 2 -->
    </joint>
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>
    
    <!-- the front right wheel -->
    <joint name="front_right_wheel_joint" type="revolute" >
        <limit lower="-0.76096" upper="0.76096" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0.127 -0.089 -0.0508" rpy="0 0 0" />
    </joint>
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>
    
    <!-- the back left wheel -->
    <joint name="back_left_wheel_joint" type="fixed" >
        <!-- <axis xyz="0 1 0" /> -->
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="-0.127 0.089 -0.0508" rpy="0 0 0" /> <!-- 5, 3.5, 2 -->
    </joint>
    <link name="back_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>
    
    <!-- the back right wheel -->
    <joint name="back_right_wheel_joint" type="fixed" >
        <!-- <axis xyz="0 1 0" /> -->
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="-0.127 -0.089 -0.0508" rpy="0 0 0" />
    </joint>
    <link name="back_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>

    <!-- XV LIDAR -->
    <xacro:rplidar_v0 
        name="rplidar" 
        parent="base_link">
        <origin 
            xyz="${lidar_x} ${lidar_y} ${lidar_z}" 
            rpy="0 0 ${lidar_yaw}" /> 
    </xacro:rplidar_v0>

    <!-- IMU -->
    <xacro:bno055_imu_v0 
        name="imu" 
        parent="base_link">
        <origin 
            xyz="${imu_x} ${imu_y} ${imu_z}" 
            rpy="0 0 0" /> 
    </xacro:bno055_imu_v0>

    <!-- ZED -->
    <xacro:zed_v0 
        name="zed" 
        parent="base_link">
        <origin 
            xyz="${zed_x} ${zed_y} ${zed_z}" 
            rpy="0 0 0" /> 
    </xacro:zed_v0>

</robot>