<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- <xacro:include filename="$(find gigatron_hardware)/urdf/common.urdf.xacro" /> -->

  <property name="zed_cam_separation" value="0.12065" /> 

  <!-- Stereolabs ZED sensor macro -->
  <xacro:macro name="zed_v0" params="name parent *origin">
  
    <!-- ZED -->
    <joint name="zed_joint" type="fixed">
       <insert_block name="origin" />
      <parent link="${parent}"/>
        <child link="zed_link"/>
    </joint>
    <link name="zed_link" type="fixed">
        <inertial>
            <mass value="0.2" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.2" ixy="0.0"  ixz="0.0"  iyy="0.2"  iyz="0.0"  izz="0.2" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.0381 0.1717 0.0317" /> <!-- ZED dimensions -->
            </geometry>
            <material name="ZEDGrey">
              <color rgba="0.5 0.5 0.5 0.5"/>
            </material>
          </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.0381 0.1717 0.0317" /> 
            </geometry>
        </collision>
    </link>

    <!-- optical rotation -->
    <joint name="zed_optical_joint" type="fixed">
        <origin xyz="${0.0381/2} 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="zed_link"/>
        <child link="zed_optical_frame"/>
    </joint>
    <link name="zed_optical_frame" />

    <!-- left camera -->
    <joint name="zed_left_camera_joint" type="fixed">
        <origin xyz="${0.0381/2} ${zed_cam_separation/2} 0" rpy="0 0 0" />
        <parent link="zed_link"/>
        <child link="left_camera_link"/>
    </joint>
    <link name="left_camera_link" />

    <joint name="left_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="left_camera_link"/>
        <child link="left_optical_frame"/>
    </joint>
    <link name="left_optical_frame" type="fixed" />

    <!-- right camera -->
    <joint name="zed_right_camera_joint" type="fixed">
        <origin xyz="${0.0381/2} -${zed_cam_separation/2} 0" rpy="0 0 0" />
        <parent link="zed_link"/>
        <child link="right_camera_link"/>
    </joint>
    <link name="right_camera_link" />

    <joint name="right_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="right_camera_link"/>
        <child link="right_optical_frame"/>
    </joint>
    <link name="right_optical_frame" />
    
  </xacro:macro>

</robot>