scan_filter_chain:
- name: inverted_forward_60_angle_filter
  type: LaserScanAngleFilter
  params:
    upper_angle: -0.52
    lower_angle: 0.52
- name: estop_range_filter
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.5
    upper_threshold: 1